version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./:/app
    restart: unless-stopped
    command: sh -c "mkdir -p /app/dist && cp -r /usr/share/nginx/html/* /app/dist && nginx -g 'daemon off;'"
    # If you need environment variables:
    # environment:
    #   - NODE_ENV=development
    #   - API_URL=https://your-backend-api.com 