version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules  # This volume prevents overwriting node_modules with host directory
    ports:
      - "5173:5173"  # Map host to port 5173
    restart: unless-stopped
    # If you need environment variables:
    # environment:
    #   - NODE_ENV=development
    #   - API_URL=https://your-backend-api.com 